version: "3.9"
services:
  mysql:
    restart: always
    container_name: "mysql"
    image: mysql:latest
    ports:
      - 3306:3306
      - 8080:8080
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=unemployment_statistics
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ../database-config:/docker-entrypoint-initdb.d